apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: assign2space
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: secret2ecr
      containers:
        - name: mysql
          image: 418213695712.dkr.ecr.us-east-1.amazonaws.com/clo835_assign2:mysql-v0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DBPWD